# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Nu8OuYUHaJX1qoXZxpjXrt-lVIw4ltJ
"""

import requests
import json

API_KEY = "Put your key here..."

def search_videos(query, max_results=5):
    url = f"https://www.googleapis.com/youtube/v3/search?part=snippet&q={query}&type=video&maxResults={max_results}&key={API_KEY}"
    response = requests.get(url)

    if response.status_code == 200:
        return response.json()['items']
    else:
        print(f"Error: {response.status_code} - {response.text}")
        return None

def get_video_comments(video_id, max_results=100):
    comments = []
    next_page_token = None

    while True:
        url = f"https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId={video_id}&maxResults={max_results}&key={API_KEY}"

        if next_page_token:
            url += f"&pageToken={next_page_token}"

        response = requests.get(url)

        if response.status_code == 200:
            data = response.json()
            for item in data.get('items', []):
                comment_data = item['snippet']['topLevelComment']['snippet']
                comment = {
                    'comment_id': item['id'],
                    'video_id': video_id,
                    'author': comment_data['authorDisplayName'],
                    'text': comment_data['textDisplay'],
                    'like_count': comment_data['likeCount'],
                    'timestamp': comment_data['publishedAt'],
                }
                comments.append(comment)

            next_page_token = data.get('nextPageToken')

            if not next_page_token:
                break
        else:
            print(f"Error: {response.status_code} - {response.text}")
            break

    return comments

def get_video_statistics(video_id):
    """Get statistics for a specific video."""
    url = f"https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&id={video_id}&key={API_KEY}"
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()['items']
        if data:
            video_data = data[0]
            statistics = {
                'video_id': video_id,
                'title': video_data['snippet']['title'],
                'description': video_data['snippet']['description'],
                'views': video_data['statistics']['viewCount'],
                'likes': video_data['statistics']['likeCount'],
                'published_at': video_data['snippet']['publishedAt'],
            }
            return statistics
    else:
        print(f"Error: {response.status_code} - {response.text}")
    return None

search_results = search_videos("pokemon", max_results=5)

if search_results:
    for result in search_results:
        video_id = result['id']['videoId']

        # Get video statistics
        stats = get_video_statistics(video_id)

        # Get video comments
        comments = get_video_comments(video_id)
else:
    print("No videos found.")

comments